spring.application.name=Rag
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=smollm:135m
spring.ai.ollama.embedding.model=nomic-embed-text:latest
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}

spring.ai.google.genai.embedding.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001

spring.ai.google.genai.chat.model=gemini-3.6-flash